// <auto-generated />
using System;
using AudioAnalyzer.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioAnalyzer.Migrations
{
    [DbContext(typeof(SongDbContext))]
    partial class SongDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("AudioAnalyzer.Models.Song", b =>
                {
                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageBandEnergyRatio")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageBandwidth")
                        .HasColumnType("REAL");

                    b.Property<float?>("AverageEnvelope")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageRootMeanSquare")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageSpectralCentroid")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageZeroCrossingRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("BeatsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalTime")
                        .HasColumnType("REAL");

                    b.HasKey("FilePath");

                    b.ToTable("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
